import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const source = (path: string) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8');

test('Telegram transport, durable outbox, inbox, drafts and bindings are isolated behind Worker compatibility exports', () => {
  const worker = source('sites/worker.js');
  const transport = source('sites/telegram/transport.js');
  const outbox = source('sites/telegram/outbox.js');
  const inbox = source('sites/telegram/inbox.js');
  const drafts = source('sites/telegram/drafts.js');
  const bindings = source('sites/telegram/bindings.js');
  const commands = source('sites/telegram/commands.js');
  const connection = source('sites/telegram/connection.js');
  const rendering = source('sites/telegram/rendering.js');
  const projectStore = source('sites/telegram/project-store.js');
  const readCommands = source('sites/telegram/read-commands.js');
  const battleAutomations = source('sites/automations/battle.js');

  assert.ok(worker.includes("from './telegram/transport.js'"));
  assert.ok(worker.includes("from './telegram/inbox.js'"));
  assert.ok(worker.includes("from './telegram/outbox.js'"));
  assert.ok(worker.includes("from './telegram/drafts.js'"));
  assert.ok(worker.includes("from './telegram/bindings.js'"));
  assert.ok(worker.includes("from './telegram/commands.js'"));
  assert.ok(worker.includes("from './telegram/connection.js'"));
  assert.ok(worker.includes("from './telegram/rendering.js'"));
  assert.ok(worker.includes("from './telegram/project-store.js'"));
  assert.ok(worker.includes("from './telegram/read-commands.js'"));
  assert.ok(worker.includes("from './automations/battle.js'"));
  assert.match(worker, /export const flushTelegramOutbox = \(env, limit = 10\) => flushTelegramOutboxModule\(env, limit, ensureSchema\)/);
  assert.doesNotMatch(worker, /const queueTelegramMessage/);
  assert.doesNotMatch(worker, /const readTelegramUpdateStatus/);
  assert.doesNotMatch(worker, /const telegramRuntimeEnv/);
  assert.doesNotMatch(worker, /const readTelegramDraft/);
  assert.doesNotMatch(worker, /INSERT INTO telegram_drafts/);
  assert.doesNotMatch(worker, /SELECT project_id\s+FROM telegram_user_chat_projects/);
  assert.doesNotMatch(worker, /const telegramCommandDistance/);
  assert.doesNotMatch(worker, /const resolveTelegramConnection/);
  assert.doesNotMatch(worker, /const renderTaskDraft/);
  assert.doesNotMatch(worker, /const telegramTasks/);
  assert.doesNotMatch(worker, /const telegramFinance/);
  assert.doesNotMatch(worker, /const telegramProjectStatus/);
  assert.doesNotMatch(worker, /INSERT INTO telegram_chat_candidates/);
  assert.doesNotMatch(worker, /UPDATE project_state[\s\S]*updated_role/);
  assert.doesNotMatch(worker, /const applyBattleAutomations/);
  assert.match(transport, /export const telegramSend/);
  assert.match(outbox, /export const telegramDurableSend/);
  assert.match(inbox, /export const claimTelegramUpdate/);
  assert.match(inbox, /export const completeTelegramUpdate/);
  assert.match(inbox, /export const failTelegramUpdate/);
  assert.match(drafts, /export const createTelegramDraft/);
  assert.match(drafts, /export const readTelegramDraft/);
  assert.match(drafts, /export const claimTelegramDraft/);
  assert.match(drafts, /export const assertTelegramDraftLease/);
  assert.match(drafts, /WHERE id = \? AND telegram_user_id = \? AND chat_id = \? AND status = 'draft' AND updated_at = \?/);
  assert.match(bindings, /WHERE telegram_user_id = \? AND chat_id = \?/);
  assert.match(bindings, /ON CONFLICT\(telegram_user_id, chat_id\) DO UPDATE SET/);
  assert.match(commands, /export const commandFromText/);
  assert.match(commands, /export const naturalTelegramCommand/);
  assert.match(commands, /export const parseTelegramExpense/);
  assert.match(connection, /export const createTelegramConnection/);
  assert.match(connection, /TELEGRAM_COMMON_CHAT_ID/);
  assert.match(rendering, /export const renderTaskDraft/);
  assert.match(rendering, /export const renderExpenseDraft/);
  assert.match(projectStore, /export const createTelegramProjectStore/);
  assert.match(readCommands, /export const createTelegramReadCommands/);
  assert.match(readCommands, /user\.role !== 'management'/);
  assert.match(battleAutomations, /export const applyBattleAutomations/);
  assert.match(projectStore, /WHERE project_id = \? AND revision = \?/);
  assert.match(outbox, /WHERE id = \? AND status = \? AND updated_at = \? AND attempts = \?/);
});
